listen: 127.0.0.1:8000  # ip:port
logFormat: text  # json, text (default), textcolour, textnocolour
logLevel: Info
LogMethodName: false
vegaAssets:
  - XYZbeta
algorithm: ByLPCommittedList
algorithmConfig:
  marketID: 4a12e42cf69da167fd265a88eef6c0a36da9f42891dad3b424884ac05faace09
defaultDisplay: TwitterHandle
defaultSort: TwitterHandle
description: A List of Liquidity Providers on the ATOM market
gracefulShutdownTimeout: 5s
headers:
  - TwitterHandle
socialURL:
  scheme: https
  host: europe-west1-vegaprotocol.cloudfunctions.net
  path: /smv/parties
vegaGraphQLURL:
  scheme: https
  host: lb.testnet.vega.xyz
  path: /query
vegaPoll: 30s
startTime: 2022-08-01T10:00:00Z
endTime: 2022-08-08T16:30:00Z
mongoConnectionString: mongodb+srv://not-required
mongoCollectionName: not-required
mongoDatabaseName: not-required
snapshotEnabled: true