listen: 127.0.0.1:8000  # ip:port
logFormat: text  # json, text (default), textcolour, textnocolour
logLevel: Info
LogMethodName: false
vegaAssets: 
- fdf0ec118d98393a7702cf72e46fc87ad680b152f64b2aac59e093ac2d688fbb
marketIDs: 
- 236c14c7f31574a2654fc45618cbd892429dc5f38000f43d8d817055131d768b
- dad90c1e90197d064f842b050e0c89b7b809881b17512ecde4297119deca5e8e
algorithm: ByPartyPositions
algorithmConfig:
  decimalPlaces: 18
defaultDisplay: Balance
defaultSort: Balance
description: A trading competition
gracefulShutdownTimeout: 5s
headers:
  - Balance
socialURL:
  scheme: https
  host: europe-west1-vegaprotocol.cloudfunctions.net
  path: /smv/parties
vegaGraphQLURL:
  scheme: https
  host: api.n12.testnet.vega.xyz
  path: /graphql
vegaPoll: 30s
startTime: 2022-12-09T09:00:00Z
endTime: 2022-12-12T14:00:00Z
mongoConnectionString: mongodb+srv://not-required
mongoCollectionName: not-required
mongoDatabaseName: not-required
twitterBlacklist:
  1355884110619828111: hello_world