listen: 127.0.0.1:8000  # ip:port
logFormat: text  # json, text (default), textcolour, textnocolour
logLevel: Info
LogMethodName: false
vegaAssets: 
- 29287681e4d9a6457d02ded602f72002a50f25749c5edfe9e9a58241b8e97ebc
algorithm: ByPartyAccountGeneralBalance
algorithmConfig:
  marketID: 14222c61742f7af62ddf5e5f0667eedc5a0082aa2362bc5563671a960b8b2078
  decimalPlaces: 18
defaultDisplay: Balance
defaultSort: Balance
description: A trading competition
gracefulShutdownTimeout: 5s
headers:
  - Balance
socialURL:
  scheme: https
  host: europe-west1-vegaprotocol.cloudfunctions.net
  path: /smv/parties
vegaGraphQLURL:
  scheme: https
  host: api.n12.testnet.vega.xyz
  path: /graphql
vegaPoll: 30s
startTime: 2022-09-20T09:00:00Z
endTime: 2022-09-23T14:00:00Z
mongoConnectionString: mongodb+srv://not-required
mongoCollectionName: not-required
mongoDatabaseName: not-required
twitterBlacklist:
  1355884110619828111: hello_world